# Generated by Django 4.2.4 on 2023-09-02 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroCliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CadastroCliente',
            new_name='Cadastro_Cliente',
        ),
    ]
